### ISSUE TITLE
Return rejected promise

### ISSUE THREAD

**Issue by simplesmiler** [broccolijs/broccoli-plugin#2]
If the promise, returned by plugin, is rejected, broccoli fails without proper message, but with the following:
```
Error: ENOTEMPTY, directory not empty
    at Error (native)
    at Object.fs.rmdirSync (fs.js:711:18)
    at rmkidsSync (<PLUGIN_ROOT_HERE>\node_modules\broccoli-plugin\node_modules\quick-temp\node_modules\rimraf\rimraf.js:247:11)
    at rmdirSync (<PLUGIN_ROOT_HERE>\node_modules\broccoli-plugin\node_modules\quick-temp\node_modules\rimraf\rimraf.js:237:7)
    at fixWinEPERMSync (<PLUGIN_ROOT_HERE>\node_modules\broccoli-plugin\node_modules\quick-temp\node_modules\rimraf\rimraf.js:150:5)
    at rimrafSync (<PLUGIN_ROOT_HERE>\node_modules\broccoli-plugin\node_modules\quick-temp\node_modules\rimraf\rimraf.js:216:26)
    at <PLUGIN_ROOT_HERE>\node_modules\broccoli-plugin\node_modules\quick-temp\node_modules\rimraf\rimraf.js:245:5
    at Array.forEach (native)
    at rmkidsSync (<PLUGIN_ROOT_HERE>\node_modules\broccoli-plugin\node_modules\quick-temp\node_modules\rimraf\rimraf.js:244:26)
    at rmdirSync (<PLUGIN_ROOT_HERE>\node_modules\broccoli-plugin\node_modules\quick-temp\node_modules\rimraf\rimraf.js:237:7)
```

Win7 x86_64, node 0.12.5.

**Comment by joliss** [comment]
Could this be a variation of https://github.com/isaacs/rimraf/issues/72?

**Comment by simplesmiler** [comment]
I guess it is closely related, but why does broccoli tries to delete files before printing the error?
The issue I'm facing is the lost error message.

**Comment by joliss** [comment]
> why does broccoli tries to delete files before printing the error?

Ah, I see the problem - the cleanup [happens](https://github.com/broccolijs/broccoli/blob/fedb8880651d5e17161d6b6128b036f7a8137af8/lib/cli.js#L37-L51) before the error is reported, so the cleanup error "wins". It's a bit tricky to change this without silently swallowing cleanup errors, or adding a bunch of extra error handling code.

I'd like to suggest that it's actually acceptable to print the cleanup error rather than the build error. If a cleanup error happens, that's so fundamental an issue that it should usually be fixed first. I realize that this is happening a lot on Windows because of isaacs/rimraf#72, but then again perhaps one could say that Broccoli is simply broken on Windows until isaacs/rimraf#72 is fixed, and this is just one of many symptoms of this brokenness.

**Comment by simplesmiler** [comment]
But would not additional `.catch` before `.finally` suffice?

**Comment by joliss** [comment]
I've thought about this some more, and I don't think the behavior should be changed. If there's a cleanup error, then that error should be reported.

**Comment by simplesmiler** [comment]
Fair enough. The isaacs/rimraf#72 is painful.
